create table CONVERTER (
    id number generated by default on null as identity,
    measure_base varchar2(500) not null,
    measure_destination varchar2(500) not null,
    ratio_to_1 number(20,10) not null,
    type varchar2(2) default 'L' not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table CONVERTER add constraint CONVERTER_PK primary key (id);
