create table MEASURE (
    id number generated by default on null as identity,
    name varchar2(500) not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table MEASURE add constraint MEASURE_PK primary key (id);
alter table MEASURE add constraint MEASURE_UK unique (name);
