
create table RECIPE_INGREDIENT (
    id number generated by default on null as identity,
    idrecipe number not null,
    name varchar2(100) not null,
    DESCRIPTION varchar2(1000) null,
    amount NUMBER(10,3) null,
    idmeasure number,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table RECIPE_INGREDIENT add constraint RECIPE_INGREDIENT_PK primary key (id);
alter table RECIPE_INGREDIENT add constraint RECIPE_INGREDIENT_FK foreign  key (idrecipe) references RECIPE(id);
alter table RECIPE_INGREDIENT add constraint RECIPE_INGREDIENT_FK2 foreign  key (idmeasure) references MEASURE(id);
