create table RECIPE (
    id number generated by default on null as identity,
    name varchar2(500) not null,
    personas number(2,0) null,
    time VARCHAR2(10) null,
    observation varchar2(4000) null,
    starrating number(2,0) null,
    tags varchar2(4000) null,
    difficulty varchar2(1) null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table RECIPE add constraint RECIPE_PK primary key (id);