create table RECIPE_STEP (
    id number generated by default on null as identity,
    idrecipe number not null,
    step number(2,0) not null,
    description varchar2(4000) not null,
    created date not null,
    created_by varchar2(255 char) not null,
    updated date not null,
    updated_by varchar2(255 char) not null
);

alter table RECIPE_STEP add constraint RECIPE_STEP_PK primary key (id);
alter table RECIPE_STEP add constraint RECIPE_STEP_FK foreign  key (idrecipe) references RECIPE(id);
alter table RECIPE_STEP add constraint RECIPE_STEP_UK unique (idrecipe, step);
